

def _monitor_safe_name(value):
    token = re.sub(r'[^A-Za-z0-9_]+', '_', value).strip('_')
    return (token or 'monitor')[:80]


def _monitor_root():
    host = me.parent() if hasattr(me, 'parent') else None
    if host is None:
        host = op('/project1')
    if host is None or not host.isCOMP:
        return None

    root = host.op('mcp_monitors')
    if root is not None:
        return root

    root = host.create('baseCOMP', 'mcp_monitors')
    root.comment = 'Auto-generated by TD MCP monitor provisioning'
    try:
        root.nodeX = me.nodeX + 300
        root.nodeY = me.nodeY
    except Exception:
        pass
    return root


def _set_first_par(node, names, value):
    for name in names:
        p = getattr(node.par, name, None)
        if p is None:
            continue
        try:
            p.val = value
        except Exception:
            try:
                setattr(node.par, name, value)
            except Exception:
                continue
        return True
    return False


def _create_or_replace(parent, node_type, name):
    existing = parent.op(name)
    if existing is not None:
        existing.destroy()
    return parent.create(node_type, name)


def _create_with_fallback(parent, node_types, name):
    last_error = None
    for node_type in node_types:
        try:
            return _create_or_replace(parent, node_type, name)
        except Exception as exc:
            last_error = exc
    raise Exception(f'Could not create DAT {name}: {last_error}')


def _destroy_monitor_nodes(paths):
    removed = []
    for node_path in paths:
        node = op(node_path)
        if node is None:
            continue
        try:
            node.destroy()
            removed.append(node_path)
        except Exception:
            continue
    return removed


def _render_chop_callback(path, channels, threshold, rate_limit):
    channels_json = repr(channels or [])
    threshold_json = repr(threshold)
    rate_limit_val = float(rate_limit or 0.0)
    return f"""import json
import time

_CHANNELS = {channels_json}
_THRESHOLD = {threshold_json}
_RATE_LIMIT = {rate_limit_val}
_LAST_EMIT = {{}}


def _json_safe(value):
    if isinstance(value, (int, float, str, bool)) or value is None:
        return value
    return str(value)


def _emit(event_type, data, key):
    now = time.time()
    previous = _LAST_EMIT.get(key, 0.0)
    if _RATE_LIMIT > 0 and now - previous < _RATE_LIMIT:
        return
    _LAST_EMIT[key] = now
    payload = {{
        "type": event_type,
        "timestamp": now,
        "data": data,
    }}

    ws = op("/project1/mcp_server/ws_client") or op("ws_client")
    if ws is not None and hasattr(ws, "sendText"):
        try:
            ws.sendText(json.dumps(payload))
            return
        except Exception:
            pass

    try:
        emitter = mod("event_emitter")
        if hasattr(emitter, "emit_event"):
            emitter.emit_event(payload)
    except Exception:
        pass


def onValueChange(channel, sampleIndex, val, prev):
    if _CHANNELS and channel.name not in _CHANNELS:
        return
    curr = float(val)
    old = float(prev)
    if _THRESHOLD is not None and abs(curr - old) < float(_THRESHOLD):
        return
    _emit(
        "chop_change",
        {{
            "path": "{path}",
            "channel": channel.name,
            "value": _json_safe(curr),
            "prev": _json_safe(old),
        }},
        "{path}:" + channel.name,
    )
    return
"""


def _render_chop_poll_callback(path, channels, threshold, rate_limit):
    channels_json = repr(channels or [])
    threshold_json = repr(threshold)
    rate_limit_val = float(rate_limit or 0.0)
    return f"""import json
import time

_PATH = {json.dumps(path)}
_CHANNELS = {channels_json}
_THRESHOLD = {threshold_json}
_RATE_LIMIT = {rate_limit_val}
_LAST_EMIT = {{}}
_LAST_VALUES = {{}}


def _json_safe(value):
    if isinstance(value, (int, float, str, bool)) or value is None:
        return value
    return str(value)


def _emit(event_type, data, key):
    now = time.time()
    previous = _LAST_EMIT.get(key, 0.0)
    if _RATE_LIMIT > 0 and now - previous < _RATE_LIMIT:
        return
    _LAST_EMIT[key] = now
    payload = {{
        "type": event_type,
        "timestamp": now,
        "data": data,
    }}

    ws = op("/project1/mcp_server/ws_client") or op("ws_client")
    if ws is not None and hasattr(ws, "sendText"):
        try:
            ws.sendText(json.dumps(payload))
            return
        except Exception:
            pass

    try:
        emitter = mod("event_emitter")
        if hasattr(emitter, "emit_event"):
            emitter.emit_event(payload)
    except Exception:
        pass


def onFrameStart(frame):
    node = op(_PATH)
    if node is None or not getattr(node, "isCHOP", False):
        return

    for channel in node.chans():
        name = channel.name
        if _CHANNELS and name not in _CHANNELS:
            continue

        try:
            values = list(channel.vals)
            current = float(values[0]) if values else 0.0
        except Exception:
            continue

        previous = _LAST_VALUES.get(name)
        _LAST_VALUES[name] = current
        if previous is None:
            continue

        if _THRESHOLD is not None and abs(current - float(previous)) < float(_THRESHOLD):
            continue

        _emit(
            "chop_change",
            {{
                "path": _PATH,
                "channel": name,
                "value": _json_safe(current),
                "prev": _json_safe(previous),
            }},
            _PATH + ":" + name,
        )
    return
"""


def _render_par_callback(path, params, threshold, rate_limit):
    params_json = repr(params or [])
    threshold_json = repr(threshold)
    rate_limit_val = float(rate_limit or 0.0)
    return f"""import json
import time

_PARAMS = {params_json}
_THRESHOLD = {threshold_json}
_RATE_LIMIT = {rate_limit_val}
_LAST_EMIT = {{}}


def _json_safe(value):
    if isinstance(value, (int, float, str, bool)) or value is None:
        return value
    return str(value)


def _emit(event_type, data, key):
    now = time.time()
    previous = _LAST_EMIT.get(key, 0.0)
    if _RATE_LIMIT > 0 and now - previous < _RATE_LIMIT:
        return
    _LAST_EMIT[key] = now
    payload = {{
        "type": event_type,
        "timestamp": now,
        "data": data,
    }}

    ws = op("/project1/mcp_server/ws_client") or op("ws_client")
    if ws is not None and hasattr(ws, "sendText"):
        try:
            ws.sendText(json.dumps(payload))
            return
        except Exception:
            pass

    try:
        emitter = mod("event_emitter")
        if hasattr(emitter, "emit_event"):
            emitter.emit_event(payload)
    except Exception:
        pass


def onValueChange(par, prev):
    if _PARAMS and par.name not in _PARAMS:
        return
    current = par.eval()
    if _THRESHOLD is not None and isinstance(current, (int, float)) and isinstance(prev, (int, float)):
        if abs(float(current) - float(prev)) < float(_THRESHOLD):
            return
    _emit(
        "par_change",
        {{
            "path": "{path}",
            "name": par.name,
            "value": _json_safe(current),
            "prev": _json_safe(prev),
        }},
        "{path}:" + par.name,
    )
    return


def onPulse(par):
    if _PARAMS and par.name not in _PARAMS:
        return
    _emit(
        "par_change",
        {{
            "path": "{path}",
            "name": par.name,
            "value": _json_safe(par.eval()),
            "pulse": True,
        }},
        "{path}:" + par.name + ":pulse",
    )
    return
"""


def _render_runtime_callback(path, event_types, rate_limit):
    event_types_json = repr(event_types or [])
    rate_limit_val = float(rate_limit or 0.0)
    return f"""import json
import time

_PATH = {json.dumps(path)}
_EVENT_TYPES = set({event_types_json})
_RATE_LIMIT = {rate_limit_val}
_LAST_EMIT = {{}}
_STATE = {{
    "cook_frame": None,
    "errors": None,
    "timeline": None,
}}


def _json_safe(value):
    if isinstance(value, (int, float, str, bool)) or value is None:
        return value
    return str(value)


def _emit(event_type, data, key):
    now = time.time()
    previous = _LAST_EMIT.get(key, 0.0)
    if _RATE_LIMIT > 0 and now - previous < _RATE_LIMIT:
        return
    _LAST_EMIT[key] = now
    payload = {{
        "type": event_type,
        "timestamp": now,
        "data": data,
    }}

    ws = op("/project1/mcp_server/ws_client") or op("ws_client")
    if ws is not None and hasattr(ws, "sendText"):
        try:
            ws.sendText(json.dumps(payload))
            return
        except Exception:
            pass

    try:
        emitter = mod("event_emitter")
        if hasattr(emitter, "emit_event"):
            emitter.emit_event(payload)
    except Exception:
        pass


def _timeline_snapshot():
    return (
        bool(project.realTime),
        int(absTime.frame),
        float(project.cookRate),
    )


def onFrameStart(frame):
    node = op(_PATH)

    if "cook_complete" in _EVENT_TYPES and node is not None:
        cook_frame = getattr(node, "cookFrame", None)
        should_emit = False
        if cook_frame is not None:
            if cook_frame != _STATE.get("cook_frame"):
                _STATE["cook_frame"] = cook_frame
                should_emit = True
        else:
            # Fallback when cookFrame is unavailable in this TD build.
            should_emit = True

        if should_emit:
            cook_time = None
            for attr in ("cookTime", "cpuCookTime", "gpuCookTime"):
                value = getattr(node, attr, None)
                if value is not None:
                    cook_time = _json_safe(value)
                    break
            _emit(
                "cook_complete",
                {{
                    "path": _PATH,
                    "frame": int(absTime.frame),
                    "cook_frame": _json_safe(cook_frame),
                    "cook_time": cook_time,
                }},
                _PATH + ":cook",
            )

    if "node_error" in _EVENT_TYPES:
        if node is None:
            state = "node_missing"
            errs = "Node missing"
            warns = ""
        else:
            try:
                errs = node.errors(recurse=False) or ""
            except Exception:
                errs = ""
            try:
                warns = node.warnings(recurse=False) or ""
            except Exception:
                warns = ""
            state = str(errs) + "|" + str(warns)

        if state != _STATE.get("errors"):
            _STATE["errors"] = state
            if errs or warns:
                _emit(
                    "node_error",
                    {{
                        "path": _PATH,
                        "errors": _json_safe(errs),
                        "warnings": _json_safe(warns),
                    }},
                    _PATH + ":error",
                )

    if "timeline" in _EVENT_TYPES:
        timeline = _timeline_snapshot()
        if timeline != _STATE.get("timeline"):
            _STATE["timeline"] = timeline
            _emit(
                "timeline",
                {{
                    "playing": bool(project.realTime),
                    "frame": int(absTime.frame),
                    "seconds": float(absTime.seconds),
                    "fps": float(project.cookRate),
                }},
                "timeline:state",
            )
    return
"""


def _provision_monitor_nodes(node, config):
    root = _monitor_root()
    if root is None:
        raise Exception('Unable to resolve monitor root COMP.')

    created = []
    warnings = []
    base = _monitor_safe_name(config['path'].strip('/'))
    event_types = config.get('event_types', [])

    if 'chop_change' in event_types:
        if not node.isCHOP:
            warnings.append('chop_change requested on non-CHOP node; skipped.')
        else:
            cb_name = f'{base}_chop_cb'
            exec_name = f'{base}_chop_exec'
            callback_dat = _create_or_replace(root, 'textDAT', cb_name)
            try:
                callback_dat.text = _render_chop_callback(
                    config['path'],
                    config.get('channels'),
                    config.get('threshold'),
                    config.get('rate_limit', 0.016),
                )
                chop_exec = _create_with_fallback(root, ('chopExecuteDAT', 'chopexecDAT'), exec_name)
                _set_first_par(chop_exec, ('active',), 1)
                _set_first_par(chop_exec, ('chop',), config['path'])
                _set_first_par(chop_exec, ('valuechange', 'onvaluechange'), 1)
                _set_first_par(chop_exec, ('callbacks', 'callbackdat', 'callback'), callback_dat.path)
                created.extend([callback_dat.path, chop_exec.path])
            except Exception:
                callback_dat.text = _render_chop_poll_callback(
                    config['path'],
                    config.get('channels'),
                    config.get('threshold'),
                    config.get('rate_limit', 0.016),
                )
                exec_dat = _create_with_fallback(root, ('executeDAT',), exec_name)
                _set_first_par(exec_dat, ('active',), 1)
                _set_first_par(exec_dat, ('framestart', 'onframestart', 'frameStart'), 1)
                _set_first_par(exec_dat, ('callbacks', 'callbackdat', 'callback'), callback_dat.path)
                try:
                    exec_dat.text = callback_dat.text
                except Exception:
                    pass
                created.extend([callback_dat.path, exec_dat.path])
                warnings.append('chopExecuteDAT unavailable; using executeDAT polling fallback.')

    if 'par_change' in event_types:
        cb_name = f'{base}_par_cb'
        exec_name = f'{base}_par_exec'
        callback_dat = _create_or_replace(root, 'textDAT', cb_name)
        callback_dat.text = _render_par_callback(
            config['path'],
            config.get('params'),
            config.get('threshold'),
            config.get('rate_limit', 0.016),
        )
        par_exec = _create_with_fallback(root, ('parameterexecuteDAT', 'parexecDAT'), exec_name)
        _set_first_par(par_exec, ('active',), 1)
        _set_first_par(par_exec, ('op', 'ops', 'targetop'), config['path'])
        _set_first_par(par_exec, ('pars', 'parameters'), ' '.join(config.get('params') or []))
        _set_first_par(par_exec, ('valuechange', 'onvaluechange'), 1)
        _set_first_par(par_exec, ('onpulse', 'pulse'), 1)
        _set_first_par(par_exec, ('callbacks', 'callbackdat', 'callback'), callback_dat.path)
        created.extend([callback_dat.path, par_exec.path])

    runtime_types = [
        event for event in ('cook_complete', 'node_error', 'timeline')
        if event in event_types
    ]
    if runtime_types:
        cb_name = f'{base}_runtime_cb'
        exec_name = f'{base}_runtime_exec'
        callback_dat = _create_or_replace(root, 'textDAT', cb_name)
        callback_dat.text = _render_runtime_callback(
            config['path'],
            runtime_types,
            config.get('rate_limit', 0.016),
        )
        try:
            exec_dat = _create_with_fallback(root, ('executeDAT',), exec_name)
            _set_first_par(exec_dat, ('active',), 1)
            _set_first_par(exec_dat, ('framestart', 'onframestart', 'frameStart'), 1)
            _set_first_par(exec_dat, ('callbacks', 'callbackdat', 'callback'), callback_dat.path)
            try:
                exec_dat.text = callback_dat.text
            except Exception:
                pass
            created.extend([callback_dat.path, exec_dat.path])
        except Exception as exc:
            warnings.append(f'Failed to provision runtime monitor DAT: {exc}')

    return created, warnings


def handle_monitor_subscribe(body):
    """Create/update monitor DATs for real-time event subscription."""
    path = body.get('path')
    if not path:
        return {'error': 'Missing required field: path'}

    node = op(path)
    if node is None:
        return {'error': f'Node not found: {path}'}

    existing = MONITOR_SUBSCRIPTIONS.get(path, {})
    if existing.get('monitor_nodes'):
        _destroy_monitor_nodes(existing.get('monitor_nodes', []))

    config = {
        'path': path,
        'event_types': body.get('event_types', ['chop_change', 'par_change']),
        'channels': body.get('channels'),
        'params': body.get('params'),
        'threshold': body.get('threshold'),
        'rate_limit': body.get('rate_limit', 0.016),
    }

    try:
        monitor_nodes, warnings = _provision_monitor_nodes(node, config)
    except Exception as exc:
        return {'error': f'Failed to provision monitors: {str(exc)}'}

    MONITOR_SUBSCRIPTIONS[path] = {
        'config': config,
        'monitor_nodes': monitor_nodes,
        'created_at': time.time(),
    }

    return {
        'success': True,
        'monitoring': config,
        'monitor_nodes': monitor_nodes,
        'warnings': warnings,
        'active_subscriptions': len(MONITOR_SUBSCRIPTIONS),
    }


def handle_monitor_unsubscribe(body):
    """Remove monitor DATs and subscription state for a path."""
    path = body.get('path')
    if not path:
        return {'error': 'Missing required field: path'}

    removed = MONITOR_SUBSCRIPTIONS.pop(path, None)
    destroyed = []
    if removed:
        destroyed = _destroy_monitor_nodes(removed.get('monitor_nodes', []))

    return {
        'success': removed is not None,
        'path': path,
        'destroyed_nodes': destroyed,
        'active_subscriptions': len(MONITOR_SUBSCRIPTIONS),
    }

