"""Plugin install / auth smoke test (v1.4.4 reliability release).

The Claude Code plugin install path reads the repo's `.mcp.json` directly.
`install.sh` / `install.ps1` generate a `TD_MCP_SHARED_SECRET` when run, but
the plugin path does not invoke them. Before v1.4.3 that misconfiguration
silently booted the server with auth required + no secret, and every
authenticated request returned 401.

The Fix #1 gate (`server.verify_auth_config`) catches this now. This suite
asserts:

1. The shipped `.mcp.json` *still* declares `TD_MCP_REQUIRE_AUTH=1`
   (if someone removes that, the shipped default changes silently).
2. With just `.mcp.json`'s env and no external secret, `verify_auth_config`
   raises and `tdpilot-dpsk4 doctor --skip-td-check` exits non-zero. Proving
   that the plugin install path is loud about its misconfiguration.
3. With `.mcp.json`'s env plus an externally-provided
   `TD_MCP_SHARED_SECRET`, `verify_auth_config` accepts and doctor's
   auth_config line is PASS.

Together these pin the whole "plugin install → auth behaviour" loop
against future drift.
"""

from __future__ import annotations

import json
import os
from pathlib import Path

import pytest

import td_mcp.server as server

REPO = Path(__file__).resolve().parent.parent
MCP_JSON = REPO / ".mcp.json"


def _shipped_mcp_env() -> dict:
    """Return the env block from the shipped .mcp.json."""
    data = json.loads(MCP_JSON.read_text(encoding="utf-8"))
    servers = data.get("mcpServers", {})
    td = next(iter(servers.values()))  # whichever key — there's only one
    return dict(td.get("env", {}))


def test_shipped_mcp_json_still_declares_require_auth():
    """If this test fails: someone changed the default auth posture in
    the plugin's shipping config. Review the change deliberately."""
    env = _shipped_mcp_env()
    assert env.get("TD_MCP_REQUIRE_AUTH") == "1", (
        f".mcp.json TD_MCP_REQUIRE_AUTH is {env.get('TD_MCP_REQUIRE_AUTH')!r}; "
        "expected '1' (the shipped default). If this is intentional, "
        "update docs/INSTALL_CLAUDE_PLUGIN.md and this test together."
    )
    # v1.4.5: autogenerate must be on so bootstrap_auth can mint a secret
    # on fresh plugin installs. Without this, the v1.4.3 fail-loud gate
    # trips deterministically on first server start — which is the
    # regression that v1.4.5 fixes.
    assert env.get("TD_MCP_AUTOGENERATE_SECRET") == "1", (
        f".mcp.json TD_MCP_AUTOGENERATE_SECRET is "
        f"{env.get('TD_MCP_AUTOGENERATE_SECRET')!r}; expected '1'. "
        "Without it, fresh plugin installs deterministically fail at "
        "startup after the v1.4.3 auth gate landed."
    )
    # The shipped config must NOT embed a literal secret — secrets are
    # per-machine, generated by auth_bootstrap or install.sh/install.ps1.
    assert "TD_MCP_SHARED_SECRET" not in env, (
        "shipped .mcp.json must not embed a literal TD_MCP_SHARED_SECRET; "
        "auth_bootstrap generates it per machine into ~/.tdpilot-dpsk4/.tdpilot-dpsk4.env."
    )


def _apply_env(monkeypatch, env: dict, *, secret: str | None = None) -> None:
    """Apply shipped .mcp.json env to the test process, optionally adding a secret."""
    for key, value in env.items():
        monkeypatch.setenv(key, str(value))
    if secret is not None:
        monkeypatch.setenv("TD_MCP_SHARED_SECRET", secret)
    else:
        monkeypatch.delenv("TD_MCP_SHARED_SECRET", raising=False)


def test_plugin_install_unconfigured_trips_auth_gate(monkeypatch):
    """Shipped .mcp.json + no external secret → `verify_auth_config` raises.

    This is the regression the v1.4.3 auth fix prevents. If this test
    passes without the fix, we've regressed.
    """
    env = _shipped_mcp_env()
    _apply_env(monkeypatch, env, secret=None)

    with pytest.raises(RuntimeError) as exc:
        server.verify_auth_config()
    assert "TD_MCP_SHARED_SECRET" in str(exc.value)
    assert "install" in str(exc.value).lower()


def test_plugin_install_unconfigured_doctor_succeeds_via_autogen(monkeypatch, capsys, tmp_path):
    """Shipped .mcp.json env (which has TD_MCP_AUTOGENERATE_SECRET=1) +
    isolated env-file location + no external secret → bootstrap_auth
    mints a secret and doctor's auth_config line is PASS.

    v1.4.5 semantics reversal vs v1.4.4: previously this test asserted
    doctor FAILED because nothing was bootstrapping the secret. The v1.4.5
    fix adds autogen via bootstrap_auth, which is now called before the
    doctor report collection, so this same starting state now succeeds.
    That's the point — it's the whole v1.4.5 regression fix.
    """
    env = _shipped_mcp_env()
    _apply_env(monkeypatch, env, secret=None)
    # Isolate the env-file write so we don't touch the user's real
    # ~/.tdpilot-dpsk4/.tdpilot-dpsk4.env.
    monkeypatch.setenv("TDPILOT_ENV_FILE", str(tmp_path / ".tdpilot-dpsk4.env"))

    with pytest.raises(SystemExit) as exc:
        server.main(["doctor", "--skip-td-check"])
    assert exc.value.code == 0, (
        "v1.4.5: shipped .mcp.json env with autogen should produce a "
        "working doctor run; if this fails the bootstrap integration regressed"
    )
    out = capsys.readouterr().out
    auth_line = next((line for line in out.splitlines() if "auth_config" in line), "")
    assert "PASS" in auth_line
    # Sanity: the env file was created in tmp, not in the user's home
    assert (tmp_path / ".tdpilot-dpsk4.env").exists()


def test_plugin_install_with_secret_passes_gate(monkeypatch):
    """Shipped .mcp.json + external secret → verify_auth_config accepts."""
    env = _shipped_mcp_env()
    _apply_env(monkeypatch, env, secret="plugin-install-secret-" + "x" * 32)
    server.verify_auth_config()  # must not raise


def test_plugin_install_with_secret_doctor_auth_passes(monkeypatch, capsys, tmp_path):
    """Shipped .mcp.json + external secret → doctor's auth_config line is PASS."""
    env = _shipped_mcp_env()
    _apply_env(monkeypatch, env, secret="plugin-install-secret-" + "x" * 32)
    # Isolate env-file writes (shipped env has AUTOGEN=1 which would touch
    # the real ~/.tdpilot-dpsk4/.tdpilot-dpsk4.env; here the secret is already set via
    # process env so bootstrap is a no-op, but we isolate defensively).
    monkeypatch.setenv("TDPILOT_ENV_FILE", str(tmp_path / ".tdpilot-dpsk4.env"))

    with pytest.raises(SystemExit):
        server.main(["doctor", "--skip-td-check"])

    out = capsys.readouterr().out
    auth_line = next((line for line in out.splitlines() if "auth_config" in line), "")
    assert "PASS" in auth_line
    assert "FAIL" not in auth_line


def test_plugin_install_disabled_auth_passes(monkeypatch):
    """Alternative install mode: auth explicitly disabled.

    If a user manually sets TD_MCP_REQUIRE_AUTH=0 (not recommended but
    allowed), the gate should not trip — there's nothing to enforce.
    """
    env = _shipped_mcp_env()
    env["TD_MCP_REQUIRE_AUTH"] = "0"
    _apply_env(monkeypatch, env, secret=None)
    server.verify_auth_config()  # must not raise


# ---------------------------------------------------------------------------
# v1.4.5: end-to-end fresh-install flow via auth_bootstrap.
# The shipped .mcp.json now has TD_MCP_AUTOGENERATE_SECRET=1, so a fresh
# plugin install with no ~/.tdpilot-dpsk4/.tdpilot-dpsk4.env file must:
#   1. boot up,
#   2. have bootstrap_auth mint a secret into an ephemeral env file,
#   3. pass verify_auth_config.
# ---------------------------------------------------------------------------


def test_fresh_plugin_install_end_to_end_bootstraps_and_passes(monkeypatch, tmp_path):
    """Reproduces the fresh-plugin-install flow that v1.4.5 fixes.

    Pre-v1.4.5: shipped .mcp.json had REQUIRE_AUTH=1 + no autogen flag,
    so bootstrap had nothing to do and verify_auth_config tripped.
    Post-v1.4.5: shipped .mcp.json adds AUTOGENERATE_SECRET=1, so
    bootstrap mints a secret and verify passes.
    """
    from td_mcp import auth_bootstrap

    env = _shipped_mcp_env()
    _apply_env(monkeypatch, env, secret=None)
    env_file = tmp_path / ".tdpilot-dpsk4.env"

    auth_bootstrap.bootstrap_auth(env_file)

    # Secret was minted into both env and file
    assert os.environ.get("TD_MCP_SHARED_SECRET")
    assert env_file.exists()
    # The gate now passes
    server.verify_auth_config()


def test_doctor_also_runs_bootstrap_before_auth_check(monkeypatch, tmp_path):
    """v1.4.5 live-test regression: `tdpilot-dpsk4 doctor` must call
    bootstrap_auth() before collecting the report, otherwise the
    auth_config line lies about needing install.sh when autogen was
    supposed to handle it.

    Caught by running (before the fix):
      TDPILOT_ENV_FILE=<tmp> TD_MCP_AUTOGENERATE_SECRET=1 \\
      TD_MCP_REQUIRE_AUTH=1 uv run tdpilot-dpsk4 doctor --skip-td-check
    → auth_config FAIL even though autogen should have minted a secret.

    The bootstrap code path was only wired into the `run` command, not
    `doctor`. v1.4.5 moves bootstrap to the top of main() for all
    non-init commands.
    """
    env_file = tmp_path / ".tdpilot-dpsk4.env"
    monkeypatch.setenv("TD_MCP_REQUIRE_AUTH", "1")
    monkeypatch.setenv("TD_MCP_AUTOGENERATE_SECRET", "1")
    monkeypatch.delenv("TD_MCP_SHARED_SECRET", raising=False)
    monkeypatch.setenv("TDPILOT_ENV_FILE", str(env_file))

    with pytest.raises(SystemExit) as exc:
        server.main(["doctor", "--skip-td-check"])

    # Bootstrap ran → secret minted → auth_config PASS → doctor exits 0
    assert exc.value.code == 0, (
        "doctor exited non-zero; bootstrap_auth probably isn't wired into the doctor command path"
    )
    assert env_file.exists(), "doctor did not trigger bootstrap_auth — env file never created"


def test_fresh_plugin_install_with_autogen_disabled_still_trips_gate(monkeypatch, tmp_path):
    """Negative control: if someone removes TD_MCP_AUTOGENERATE_SECRET=1
    from .mcp.json, the fail-loud behavior returns. This is by design —
    bootstrap_auth is opt-in, not silent."""
    from td_mcp import auth_bootstrap

    env = _shipped_mcp_env()
    # Simulate the mis-configuration: autogen removed
    env.pop("TD_MCP_AUTOGENERATE_SECRET", None)
    _apply_env(monkeypatch, env, secret=None)
    monkeypatch.delenv("TD_MCP_AUTOGENERATE_SECRET", raising=False)
    env_file = tmp_path / ".tdpilot-dpsk4.env"

    auth_bootstrap.bootstrap_auth(env_file)

    # No secret should have been generated
    assert "TD_MCP_SHARED_SECRET" not in os.environ
    assert not env_file.exists()
    # Gate trips
    with pytest.raises(RuntimeError):
        server.verify_auth_config()
